DROP TABLE IF EXISTS patients;
CREATE TABLE patients (
  id INTEGER PRIMARY KEY,
  name TEXT, dob TEXT
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER timeTrigger BEFORE UPDATE ON patients BEGIN
  UPDATE patients SET updated_at = CURRENT_TIMESTAMP WHERE id = new.id;
END;

DROP TABLE IF EXISTS doctors;
CREATE TABLE doctors (
  id INTEGER PRIMARY KEY,
  name TEXT, email TEXT
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER docTrigger BEFORE UPDATE ON doctors BEGIN
  UPDATE doctors SET updated_at = CURRENT_TIMESTAMP WHERE id = new.id;
END;

DROP TABLE IF EXISTS boards;
CREATE TABLE boards (
  id INTEGER PRIMARY KEY,
  name TEXT, dob TEXT
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER timeTrigger BEFORE UPDATE ON boards BEGIN
  UPDATE boards SET updated_at = CURRENT_TIMESTAMP WHERE id = new.id;
END;
DROP TABLE IF EXISTS patients;

CREATE TABLE patients (
  id INTEGER PRIMARY KEY,
  name TEXT, dob TEXT
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER timeTrigger BEFORE UPDATE ON patients BEGIN
  UPDATE patients SET updated_at = CURRENT_TIMESTAMP WHERE id = new.id;
END;
